version: '3.8'

services:
  blazor_calendar:
    image: blazor.family.calendar.v.01
    build:
      context: .
      dockerfile: ./blazor.famely.calendar/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DefaultConnection='DataSource=/app/Data/app.db;Cache=Shared'
      - CalendarConnection='DataSource=/app/Data/calendar.db;Cache=Shared'
    volumes:
      - "/home/greg/RiderProjects/blazor.famely.calendar/blazor.famely.calendar/Data/app.db:/app/Data/app.db"
      - "/home/greg/RiderProjects/blazor.famely.calendar/blazor.famely.calendar/Data/calendar.db:/app/Data/calendar.db"
    restart: always